/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andrew' at '20/11/15 16:40' with Gradle 2.5-rc-2
 *
 * @author andrew, @date 20/11/15 16:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
